### ISSUE TITLE
Master branch does not seem to be working

### ISSUE THREAD

**Issue by jhortenstine** [mbmccormick/Milkman#131]
I was going to try fixing some bugs but it seems like Master is not in a workable state. Steps taken:
1. Downloaded master
2. Used VS 2013 Express
3. Compiled Milkman.WindowsPhone
4. Started Debugger
5. Noticed the app seemed to do nothing

I was curious if I am doing something wrong (I am new to github) or if there was a way for me to contribute to this project?

**Comment by mbmccormick** [comment]
Well that's a bummer. Sorry about that!

To confirm, the emulator launches (start screen, etc. visible) and the app gets deployed (Milkman shows up in app list)? Or does it even get that far?

Thanks!

## 

Matt McCormick

Sent from my Windows Phone

**Comment by jhortenstine** [comment]
Yes, the emulator launches and the app gets deployed. I just deployed it to my device and I have the same issue. The icons are just a box (defaults) and when you click on it then it is just a blank page.

By the way, I am getting a:
Milkman.Windows\MainPage.xaml(59,30): XamlCompiler error WMC0001: Unknown type 'TaskItemControl' in XML namespace 'using:MilkmanMX.Controls'
when compiling the entire thing. That is for the Windows project and not the Windows Phone project.

**Comment by jhortenstine** [comment]
I guess I should note that I did this several months ago (possibly a year or more) and successfully had it running on my device.

**Comment by mbmccormick** [comment]
Aha! The `master` branch is unfortunately a work in progress (attempting to convert to Universal Store app). The stable branch with the latest Windows Phone app for Milkman is on the `wp8dev` branch. I have modified the GitHub repository such that `wp8dev` is the default branch.

Sorry about this! :frowning: 

I (and the Milkman users) are appreciative for any contributions you make! :+1:
