### ISSUE TITLE
It appears that "Working on rebranding." is incomplete

### ISSUE THREAD

**Issue by jhortenstine** [mbmccormick/Milkman#132]
I compiled the app with the latest in the wp8dev branch and now the various controls are essentially invisible because it is white on white. Do all the controls need to have their color changed and if so then what was the choice?

**Comment by mbmccormick** [comment]
Bummer, sorry you are having so many issues with this. It looks like this is a work in progress that I never finished. Feel free to revert my changes, if that means bug fixes or other contributions! :smile: 

I think this was the last known good: 2a7faa2f7cda1f134c2f2c85e7182981a4804cd2
